import { NextPageContext } from "next";
import { getSession, signOut } from "next-auth/react";
import Head from "next/head";

import useCurrentUser from "@/hooks/useCurrentUser";

export async function getServerSideProps(context: NextPageContext) {
  const session = await getSession(context);

  if (!session) {
    return {
      redirect: {
        destination: "/auth",
        permanent: false,
      },
    };
  }

  return {
    props: {},
  };
}

export default function Home() {
  const { data: user } = useCurrentUser();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1 className="text-2xl text-green-500">Netflix clone</h1>
        <h2 className="text-xl text-white">Welcome {user?.name}</h2>
        <button className="h-10 w-full bg-white" onClick={() => signOut()}>
          Log out
        </button>
      </main>
    </>
  );
}
